In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as snf
import seaborn as sns

In [46]:
data_as = pd.read_csv("As_DD_2012.csv", delimiter=";")
data_bap = pd.read_csv("B(a)P_DD_2012.csv", delimiter=";")
data_cd = pd.read_csv("Cd_DD_2012.csv", delimiter=";")
data_ni = pd.read_csv("Ni_DD_2012.csv", delimiter=";")
data_pb = pd.read_csv("Pb_DD_2012.csv", delimiter=";")
data_pm10 = pd.read_csv("PM10_DD_2012.csv", delimiter=";")
data_pm25 = pd.read_csv("PM2.5_DD_2012.csv", delimiter=";")

In [48]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [50]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [52]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [54]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [55]:
all_data["MEDIA MENSUAL"] = medias

In [56]:
result_12 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [57]:
result_12.MEDIAANUAL_EMISION = result_12.MEDIAANUAL_EMISION.round(4)

In [58]:
result_12

    EMISION  PROVINCIA  ANNO  MEDIAANUAL_EMISION
0        As          1  2012              0.3552
1        As          3  2012              0.2681
2        As          4  2012              0.5523
3        As          6  2012              0.3676
4        As          7  2012              1.1795
..      ...        ...   ...                 ...
199      Pb         45  2012              0.0025
200      Pb         46  2012              0.0034
201      Pb         47  2012              0.0101
202      Pb         48  2012              0.0498
203      Pb         49  2012              0.0018

[204 rows x 4 columns]

In [59]:
data_as = pd.read_csv("As_2013_DD.csv", delimiter=";")
data_bap = pd.read_csv("BaP_2013_DD.csv", delimiter=";")
data_cd = pd.read_csv("Cd_2013_DD.csv", delimiter=";")
data_ni = pd.read_csv("Ni_2013_DD.csv", delimiter=";")
data_pb = pd.read_csv("Pb_2013_DD.csv", delimiter=";")
data_pm10 = pd.read_csv("PM10_2013_DD.csv", delimiter=";")
data_pm25 = pd.read_csv("PM2.5_2013_DD.csv", delimiter=";")

In [60]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [61]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [70]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [71]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [72]:
all_data["MEDIA MENSUAL"] = medias

In [74]:
result_13 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [75]:
result_13.MEDIAANUAL_EMISION = result_13.MEDIAANUAL_EMISION.round(4)

In [76]:
result_13

    EMISION  PROVINCIA  ANNO  MEDIAANUAL_EMISION
0        As          1  2013              0.2968
1        As          2  2013              0.7000
2        As          3  2013              0.1855
3        As          4  2013              0.4211
4        As          6  2013              0.3231
..      ...        ...   ...                 ...
221      Pb         45  2013              0.0013
222      Pb         46  2013              0.0019
223      Pb         47  2013              0.0585
224      Pb         48  2013              0.0375
225      Pb         50  2013              0.0025

[226 rows x 4 columns]

In [77]:
data_as = pd.read_csv("As_DD_2014.csv")
data_bap = pd.read_csv("B(a)P_DD_2014.csv")
data_cd = pd.read_csv("Cd_DD_2014.csv")
data_ni = pd.read_csv("Ni_DD_2014.csv")
data_pb = pd.read_csv("Pb_DD_2014.csv")
data_pm10 = pd.read_csv("PM10_DD_2014.csv")
data_pm25 = pd.read_csv("PM2.5_DD_2014.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'As_DD_2014.csv'

In [ ]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [ ]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [ ]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [ ]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [ ]:
all_data["MEDIA MENSUAL"] = medias

In [ ]:
result_14 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [ ]:
result_14.MEDIAANUAL_EMISION = result_14.MEDIAANUAL_EMISION.round(4)

In [ ]:
result_14

In [ ]:
data_as = pd.read_csv("As_DD_2015.csv")
data_bap = pd.read_csv("B(a)P_DD_2015.csv")
data_cd = pd.read_csv("Cd_DD_2015.csv")
data_ni = pd.read_csv("Ni_DD_2015.csv")
data_pb = pd.read_csv("Pb_DD_2015.csv")
data_pm10 = pd.read_csv("PM10_DD_2015.csv")
data_pm25 = pd.read_csv("PM2.5_DD_2015.csv")

In [ ]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [ ]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [88]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [89]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [91]:
all_data["MEDIA MENSUAL"] = medias

In [92]:
result_15 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [93]:
result_15.MEDIAANUAL_EMISION = result_15.MEDIAANUAL_EMISION.round(4)

In [94]:
result_15

    EMISION  PROVINCIA  ANNO  MEDIAANUAL_EMISION
0        As          1  2013              0.2968
1        As          2  2013              0.7000
2        As          3  2013              0.1855
3        As          4  2013              0.4211
4        As          6  2013              0.3231
..      ...        ...   ...                 ...
221      Pb         45  2013              0.0013
222      Pb         46  2013              0.0019
223      Pb         47  2013              0.0585
224      Pb         48  2013              0.0375
225      Pb         50  2013              0.0025

[226 rows x 4 columns]

In [95]:
data_as = pd.read_csv("As_DD_2016.csv")
data_bap = pd.read_csv("B(a)P_DD_2016.csv")
data_cd = pd.read_csv("Cd_DD_2016.csv")
data_ni = pd.read_csv("Ni_DD_2016.csv")
data_pb = pd.read_csv("Pb_DD_2016.csv")
data_pm10 = pd.read_csv("PM10_DD_2016.csv")
data_pm25 = pd.read_csv("PM25_DD_2016.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'As_DD_2016.csv'

In [ ]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [ ]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [ ]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [ ]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [ ]:
all_data["MEDIA MENSUAL"] = medias

In [ ]:
result_16 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [96]:
result_16.MEDIAANUAL_EMISION = result_16.MEDIAANUAL_EMISION.round(4)

NameError: name 'result_16' is not defined

In [105]:
result_16

NameError: name 'result_16' is not defined

In [ ]:
data_as = pd.read_csv("As_DD_2017.csv", delimiter = ";")
data_bap = pd.read_csv("B(a)P_DD_2017.csv", delimiter = ";")
data_cd = pd.read_csv("Cd_DD_2017.csv", delimiter = ";")
data_ni = pd.read_csv("Ni_DD_2017.csv", delimiter = ";")
data_pb = pd.read_csv("Pb_DD_2017.csv", delimiter = ";")
data_pm10 = pd.read_csv("PM10_DD_2017.csv", delimiter = ";")
data_pm25 = pd.read_csv("PM2.5_DD_2017.csv", delimiter = ";")

In [108]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [110]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [112]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [113]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [115]:
all_data["MEDIA MENSUAL"] = medias

In [116]:
result_17 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [117]:
result_17.MEDIAANUAL_EMISION = result_17.MEDIAANUAL_EMISION.round(4)

In [118]:
result_17

    EMISION  PROVINCIA  ANNO  MEDIAANUAL_EMISION
0        As          1  2013              0.2968
1        As          2  2013              0.7000
2        As          3  2013              0.1855
3        As          4  2013              0.4211
4        As          6  2013              0.3231
..      ...        ...   ...                 ...
221      Pb         45  2013              0.0013
222      Pb         46  2013              0.0019
223      Pb         47  2013              0.0585
224      Pb         48  2013              0.0375
225      Pb         50  2013              0.0025

[226 rows x 4 columns]

In [119]:
data_as = pd.read_csv("As_DD_2018.csv", delimiter = ";")
data_bap = pd.read_csv("B(a)P_DD_2018.csv", delimiter = ";")
data_cd = pd.read_csv("Cd_DD_2018.csv", delimiter = ";")
data_ni = pd.read_csv("Ni_DD_2018.csv", delimiter = ";")
data_pb = pd.read_csv("Pb_DD_2018.csv", delimiter = ";")
data_pm10 = pd.read_csv("PM10_DD_2018.csv", delimiter = ";")
data_pm25 = pd.read_csv("PM2.5_DD_2018.csv", delimiter = ";")

In [120]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [121]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [122]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [123]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [124]:
all_data["MEDIA MENSUAL"] = medias

In [125]:
result_18 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [126]:
result_18.MEDIAANUAL_EMISION = result_18.MEDIAANUAL_EMISION.round(4)

In [127]:
result_18

    EMISION  PROVINCIA  ANNO  MEDIAANUAL_EMISION
0        As          1  2018              0.3618
1        As          2  2018              0.3485
2        As          3  2018              0.2237
3        As          4  2018              0.2607
4        As          6  2018              0.3903
..      ...        ...   ...                 ...
267      Pb         41  2018              0.0026
268      Pb         43  2018              0.0025
269      Pb         45  2018              0.0014
270      Pb         46  2018              0.0103
271      Pb         48  2018              0.0209

[272 rows x 4 columns]

In [128]:
data_as = pd.read_csv("As_DD_2019.csv", delimiter = ";")
data_bap = pd.read_csv("BaP_DD_2019.csv", delimiter = ";")
data_cd = pd.read_csv("Cd_DD_2019.csv", delimiter = ";")
data_ni = pd.read_csv("Ni_DD_2019.csv", delimiter = ";")
data_pb = pd.read_csv("Pb_DD_2019.csv", delimiter = ";")
data_pm10 = pd.read_csv("PM10_DD_2019.csv", delimiter = ";")
data_pm25 = pd.read_csv("PM25_DD_2019.csv", delimiter = ";")

In [129]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [138]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [139]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [140]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [141]:
all_data["MEDIA MENSUAL"] = medias

In [143]:
result_19 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [144]:
result_19.MEDIAANUAL_EMISION = result_19.MEDIAANUAL_EMISION.round(4)

In [145]:
result_19

    EMISION  PROVINCIA  ANNO  MEDIAANUAL_EMISION
0        As          1  2019              0.3449
1        As          2  2019              0.5513
2        As          3  2019              0.3643
3        As          4  2019              0.5208
4        As          6  2019              0.4173
..      ...        ...   ...                 ...
231      Pb         43  2019              0.0025
232      Pb         45  2019              0.0013
233      Pb         46  2019              0.0102
234      Pb         47  2019              0.0124
235      Pb         48  2019              0.0189

[236 rows x 4 columns]

In [146]:
data_as = pd.read_csv("As_DD_2020.csv", delimiter = ";")
data_bap = pd.read_csv("B(a)P_DD_2020.csv", delimiter = ";")
data_cd = pd.read_csv("Cd_DD_2020.csv", delimiter = ";")
data_ni = pd.read_csv("Ni_DD_2020.csv", delimiter = ";")
data_pb = pd.read_csv("Pb_DD_2020.csv", delimiter = ";")
data_pm10 = pd.read_csv("PM10_DD_2020.csv", delimiter = ";")
data_pm25 = pd.read_csv("PM2.5_DD_2020.csv", delimiter = ";")

In [147]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [148]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [149]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [150]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [151]:
all_data["MEDIA MENSUAL"] = medias

In [152]:
result_20 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [153]:
result_20.MEDIAANUAL_EMISION = result_20.MEDIAANUAL_EMISION.round(4)

In [154]:
result_20

    EMISION  PROVINCIA  ANNO  MEDIAANUAL_EMISION
0        As          1  2020              0.3183
1        As          2  2020              0.4175
2        As          3  2020              0.7493
3        As          4  2020              0.4190
4        As          6  2020              0.4149
..      ...        ...   ...                 ...
255      Pb         45  2020              0.0011
256      Pb         46  2020              0.0103
257      Pb         47  2020              0.0229
258      Pb         48  2020              0.0140
259      Pb         50  2020              0.0055

[260 rows x 4 columns]

In [155]:
data_as = pd.read_csv("As_DD_2021.csv", delimiter = ";")
data_bap = pd.read_csv("BaP_DD_2021.csv", delimiter = ";")
data_cd = pd.read_csv("Cd_DD_2021.csv", delimiter = ";")
data_ni = pd.read_csv("Ni_DD_2021.csv", delimiter = ";")
data_pb = pd.read_csv("Pb_DD_2021.csv", delimiter = ";")
data_pm10 = pd.read_csv("PM10_DD_2021.csv", delimiter = ";")
data_pm25 = pd.read_csv("PM25_DD_2021.csv", delimiter = ";")

In [156]:
data_as["EMISION"] = "As"
data_bap["EMISION"] = "BaP"
data_cd["EMISION"] = "Cd"
data_ni["EMISION"] = "Ni"
data_pb["EMISION"] = "Pb"
data_pm10["EMISION"] = "PM10"
data_pm25["EMISION"] = "PM25"

In [157]:
all_data = pd.concat([data_as, data_bap, data_cd, data_ni, data_pb, data_pm10, data_pm25], ignore_index=True)

In [158]:
day_columns = [f'D{i:02}' for i in range(1, 32)]
all_data[day_columns] = all_data[day_columns].interpolate(axis=1, method='linear', limit_direction='both')

In [159]:
medias = []
for i in range(len(all_data)):
    row = all_data.loc[i, day_columns]
    if row.count() >= 15:
        valor_media = row.mean()
    else:
        valor_media = np.nan
    medias.append(valor_media)

In [160]:
all_data["MEDIA MENSUAL"] = medias

In [161]:
result_21 = all_data.groupby(["EMISION", "PROVINCIA", "ANNO"]).agg(
    MEDIAANUAL_EMISION=pd.NamedAgg(column="MEDIA MENSUAL", aggfunc="mean")
).reset_index()

In [162]:
result_21.MEDIAANUAL_EMISION = result_21.MEDIAANUAL_EMISION.round(4)

In [163]:
result_21

    EMISION  PROVINCIA  ANNO  MEDIAANUAL_EMISION
0        As          1  2021              0.3303
1        As          2  2021              0.3981
2        As          3  2021              0.2227
3        As          4  2021              0.3760
4        As          5  2021              0.2651
..      ...        ...   ...                 ...
280      Pb         47  2021              0.0230
281      Pb         48  2021              0.0200
282      Pb         49  2021              0.0018
283      Pb         50  2021              0.0045
284      Pb         51  2021              0.0200

[285 rows x 4 columns]

In [164]:
data_concatenada = pd.concat([result_12, result_13, result_14, result_15, result_16, result_17, result_18, result_19, result_20, result_21], ignore_index=True)

NameError: name 'result_14' is not defined

In [ ]:
data_concatenada.to_csv('data_calidad_aire_anual.csv', index=False)

In [35]:
data_2012 = pd.read_csv("Hospitalizaciones 2012.csv", delimiter="\t", encoding="iso-8859-1")
data_2013 = pd.read_csv("Hospitalizaciones 2013.csv", delimiter="\t", encoding="iso-8859-1")
data_2014 = pd.read_csv("Hospitalizaciones 2014.csv", delimiter="\t", encoding="iso-8859-1")
data_2015 = pd.read_csv("Hospitalizaciones 2015.csv", delimiter="\t", encoding="utf-8")
data_2016 = pd.read_csv("Hospitalizaciones 2016.csv", delimiter="\t", encoding="iso-8859-1")
data_2017 = pd.read_csv("Hospitalizaciones 2017.csv", delimiter="\t", encoding="iso-8859-1")
data_2018 = pd.read_csv("Hospitalizaciones 2018.csv", delimiter="\t", encoding="iso-8859-1")
data_2019 = pd.read_csv("Hospitalizaciones 2019.csv", delimiter="\t", encoding="iso-8859-1")
data_2020 = pd.read_csv("Hospitalizaciones 2020.csv", delimiter="\t", encoding="iso-8859-1")
data_2021 = pd.read_csv("Hospitalizaciones 2021.csv", delimiter="\t", encoding="iso-8859-1")
data_calidad_aire_anual = pd.read_csv("data_calidad_aire_anual.csv", delimiter=",", encoding="iso-8859-1")

In [226]:

data_2012['Provincia, Comunidad y Ciudad autÃ³noma de residencia'] = data_2012['Provincia, Comunidad y Ciudad autÃ³noma de residencia'].str.lower().replace( {
    "araba/Ã¡lava": 1,
    "albacete": 2,
    "alicante/alacant": 3,
    "almerÃ­a": 4,
    "Ã¡vila": 5,
    "badajoz": 6,
    "balears, illes": 7,
    "barcelona": 8,
    "burgos": 9,
    "cÃ¡ceres": 10,
    "cÃ¡diz": 11,
    "castellÃ³n/castellÃ³": 12,
    "ciudad real": 13,
    "cÃ³rdoba": 14,
    "corunÌƒa, a": 15,
    "cuenca": 16,
    "girona": 17,
    "granada": 18,
    "guadalajara": 19,
    "gipuzkoa": 20,
    "huelva": 21,
    "huesca": 22,
    "jaÃ©n": 23,
    "leÃ³n": 24,
    "lleida": 25,
    "rioja, la": 26,
    "lugo": 27,
    "madrid, comunidad de": 28,
    "mÃ¡laga": 29,
    "murcia, regiÃ³n de": 30,
    "navarra, comunidad foral de": 31,
    "ourense": 32,
    "asturias, principado de": 33,
    "palencia": 34,
    "palmas, las": 35,
    "pontevedra": 36,
    "salamanca": 37,
    "santa cruz de tenerife": 38,
    "cantabria": 39,
    "segovia": 40,
    "sevilla": 41,
    "soria": 42,
    "tarragona": 43,
    "teruel": 44,
    "toledo": 45,
    "valencia/valÃ¨ncia": 46,
    "valladolid": 47,
    "bizkaia": 48,
    "zamora": 49,
    "zaragoza": 50,
    "ceuta": 51,
    "melilla": 52
}
                                                                                                                 )   
data_2012.head(50)

,"Provincia, Comunidad y Ciudad autÃ³noma de residencia",DiagnÃ³stico principal (CIE9MC),Sexo,Total
0,4,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Ambos sexos,3.296
1,4,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Hombres,2.615
2,4,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Mujeres,681
3,4,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Ambos sexos,2.271
4,4,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Hombres,1.171
5,4,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Mujeres,1.100
6,4,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Ambos sexos,43.504
7,4,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Hombres,26.332
8,4,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Mujeres,17.172
9,4,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Ambos sexos,5.920
10,4,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Hombres,3.098
11,4,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Mujeres,2.822
12,4,466 Bronquitis y bronquiolitis aguda,Ambos sexos,3.808
13,4,466 Bronquitis y bronquiolitis aguda,Hombres,1.916
14,4,466 Bronquitis y bronquiolitis aguda,Mujeres,1.892
15,4,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Ambos sexos,353
16,4,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Hombres,171
17,4,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Mujeres,182
18,4,Resto (460-478) Otras infecciones respiratoria...,Ambos sexos,1.759
19,4,Resto (460-478) Otras infecciones respiratoria...,Hombres,1.011
20,4,Resto (460-478) Otras infecciones respiratoria...,Mujeres,748
21,4,480-486 NeumonÃ­a,Ambos sexos,11.514
22,4,480-486 NeumonÃ­a,Hombres,7.381
23,4,480-486 NeumonÃ­a,Mujeres,4.133
24,4,487-488 Gripe,Ambos sexos,57
25,4,487-488 Gripe,Hombres,21
26,4,487-488 Gripe,Mujeres,36
27,4,"490-492,494,496 Enfermedad pulmonar obstructiv...",Ambos sexos,6.508
28,4,"490-492,494,496 Enfermedad pulmonar obstructiv...",Hombres,5.637
29,4,"490-492,494,496 Enfermedad pulmonar obstructiv...",Mujeres,871
30,4,493 Asma,Ambos sexos,1.940
31,4,493 Asma,Hombres,526
32,4,493 Asma,Mujeres,1.414
33,11,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Ambos sexos,7.434
34,11,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Hombres,6.505
35,11,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Mujeres,929
36,11,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Ambos sexos,2.941
37,11,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Hombres,1.228
38,11,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Mujeres,1.713
39,11,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Ambos sexos,72.774
40,11,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Hombres,43.326
41,11,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Mujeres,29.448
42,11,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Ambos sexos,12.727
43,11,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Hombres,6.685
44,11,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Mujeres,6.042
45,11,466 Bronquitis y bronquiolitis aguda,Ambos sexos,8.029
46,11,466 Bronquitis y bronquiolitis aguda,Hombres,3.997
47,11,466 Bronquitis y bronquiolitis aguda,Mujeres,4.032
48,11,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Ambos sexos,675
49,11,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Hombres,363

In [228]:
filtro = data_2012['Provincia, Comunidad y Ciudad autÃ³noma de residencia'] == 33
data_2012[filtro]

,"Provincia, Comunidad y Ciudad autÃ³noma de residencia",DiagnÃ³stico principal (CIE9MC),Sexo,Total
363,33,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Ambos sexos,11.116
364,33,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Hombres,8.824
365,33,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Mujeres,2.291
366,33,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Ambos sexos,5.464
367,33,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Hombres,2.366
368,33,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Mujeres,3.097
369,33,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Ambos sexos,109.822
370,33,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Hombres,63.748
371,33,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Mujeres,46.074
372,33,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Ambos sexos,6.516
373,33,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Hombres,3.318
374,33,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Mujeres,3.197
375,33,466 Bronquitis y bronquiolitis aguda,Ambos sexos,2.945
376,33,466 Bronquitis y bronquiolitis aguda,Hombres,1.209
377,33,466 Bronquitis y bronquiolitis aguda,Mujeres,1.736
378,33,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Ambos sexos,421
379,33,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Hombres,242
380,33,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Mujeres,180
381,33,Resto (460-478) Otras infecciones respiratoria...,Ambos sexos,3.149
382,33,Resto (460-478) Otras infecciones respiratoria...,Hombres,1.868
383,33,Resto (460-478) Otras infecciones respiratoria...,Mujeres,1.281
384,33,480-486 NeumonÃ­a,Ambos sexos,24.377
385,33,480-486 NeumonÃ­a,Hombres,14.555
386,33,480-486 NeumonÃ­a,Mujeres,9.823
387,33,487-488 Gripe,Ambos sexos,382
388,33,487-488 Gripe,Hombres,191
389,33,487-488 Gripe,Mujeres,191
390,33,"490-492,494,496 Enfermedad pulmonar obstructiv...",Ambos sexos,22.993
391,33,"490-492,494,496 Enfermedad pulmonar obstructiv...",Hombres,19.294
392,33,"490-492,494,496 Enfermedad pulmonar obstructiv...",Mujeres,3.698
393,33,493 Asma,Ambos sexos,10.238
394,33,493 Asma,Hombres,3.125
395,33,493 Asma,Mujeres,7.113

In [230]:
data_2012.rename(
    columns = {'Provincia, Comunidad y Ciudad autÃ³noma de residencia': 'Provincia_ID'},
    inplace = True
)

In [237]:
data_2012.to_csv('Hospitalizaciones_2012.csv', index = False)

In [9]:
data_2013['Provincia, Comunidad y Ciudad autÃ³noma de residencia'] = data_2013['Provincia, Comunidad y Ciudad autÃ³noma de residencia'].str.lower().replace( {
    "araba/Ã¡lava": 1,
    "albacete": 2,
    "alicante/alacant": 3,
    "almerÃ­a": 4,
    "Ã¡vila": 5,
    "badajoz": 6,
    "balears, illes": 7,
    "barcelona": 8,
    "burgos": 9,
    "cÃ¡ceres": 10,
    "cÃ¡diz": 11,
    "castellÃ³n/castellÃ³": 12,
    "ciudad real": 13,
    "cÃ³rdoba": 14,
    "corunÌƒa, a": 15,
    "cuenca": 16,
    "girona": 17,
    "granada": 18,
    "guadalajara": 19,
    "gipuzkoa": 20,
    "huelva": 21,
    "huesca": 22,
    "jaÃ©n": 23,
    "leÃ³n": 24,
    "lleida": 25,
    "rioja, la": 26,
    "lugo": 27,
    "madrid, comunidad de": 28,
    "mÃ¡laga": 29,
    "murcia, regiÃ³n de": 30,
    "navarra, comunidad foral de": 31,
    "ourense": 32,
    "asturias, principado de": 33,
    "palencia": 34,
    "palmas, las": 35,
    "pontevedra": 36,
    "salamanca": 37,
    "santa cruz de tenerife": 38,
    "cantabria": 39,
    "segovia": 40,
    "sevilla": 41,
    "soria": 42,
    "tarragona": 43,
    "teruel": 44,
    "toledo": 45,
    "valencia/valÃ¨ncia": 46,
    "valladolid": 47,
    "bizkaia": 48,
    "zamora": 49,
    "zaragoza": 50,
    "ceuta": 51,
    "melilla": 52
}
                                                                                                                 )   
data_2013.head(50)

,"Provincia, Comunidad y Ciudad autÃ³noma de residencia",Sexo,DiagnÃ³stico principal (CIE9MC),Total
0,4,Ambos sexos,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",4.027
1,4,Ambos sexos,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,1.927
2,4,Ambos sexos,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,49.409
3,4,Ambos sexos,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,7.469
4,4,Ambos sexos,466 Bronquitis y bronquiolitis aguda,5.578
5,4,Ambos sexos,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,264
6,4,Ambos sexos,Resto (460-478) Otras infecciones respiratoria...,1.627
7,4,Ambos sexos,480-486 NeumonÃ­a,12.789
8,4,Ambos sexos,487-488 Gripe,203
9,4,Ambos sexos,"490-492,494,496 Enfermedad pulmonar obstructiv...",8.189
10,4,Ambos sexos,493 Asma,2.107
11,4,Hombres,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",3.282
12,4,Hombres,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,832
13,4,Hombres,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,29.451
14,4,Hombres,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,3.683
15,4,Hombres,466 Bronquitis y bronquiolitis aguda,2.626
16,4,Hombres,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,137
17,4,Hombres,Resto (460-478) Otras infecciones respiratoria...,920
18,4,Hombres,480-486 NeumonÃ­a,7.813
19,4,Hombres,487-488 Gripe,115
20,4,Hombres,"490-492,494,496 Enfermedad pulmonar obstructiv...",7.070
21,4,Hombres,493 Asma,577
22,4,Mujeres,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",745
23,4,Mujeres,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,1.095
24,4,Mujeres,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,19.958
25,4,Mujeres,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,3.786
26,4,Mujeres,466 Bronquitis y bronquiolitis aguda,2.952
27,4,Mujeres,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,127
28,4,Mujeres,Resto (460-478) Otras infecciones respiratoria...,707
29,4,Mujeres,480-486 NeumonÃ­a,4.976
30,4,Mujeres,487-488 Gripe,88
31,4,Mujeres,"490-492,494,496 Enfermedad pulmonar obstructiv...",1.119
32,4,Mujeres,493 Asma,1.530
33,11,Ambos sexos,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",7.440
34,11,Ambos sexos,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,2.885
35,11,Ambos sexos,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,72.629
36,11,Ambos sexos,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,12.618
37,11,Ambos sexos,466 Bronquitis y bronquiolitis aguda,7.499
38,11,Ambos sexos,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,617
39,11,Ambos sexos,Resto (460-478) Otras infecciones respiratoria...,4.502
40,11,Ambos sexos,480-486 NeumonÃ­a,17.052
41,11,Ambos sexos,487-488 Gripe,170
42,11,Ambos sexos,"490-492,494,496 Enfermedad pulmonar obstructiv...",10.068
43,11,Ambos sexos,493 Asma,2.436
44,11,Hombres,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",6.111
45,11,Hombres,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,1.413
46,11,Hombres,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,42.705
47,11,Hombres,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,6.340
48,11,Hombres,466 Bronquitis y bronquiolitis aguda,3.451
49,11,Hombres,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,302

In [247]:
data_2013.rename(
    columns = {'Provincia, Comunidad y Ciudad autÃ³noma de residencia': 'Provincia_ID'},
    inplace = True
)
data_2013

,Provincia_ID,Sexo,DiagnÃ³stico principal (CIE9MC),Total
0,4,Ambos sexos,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",4.027
1,4,Ambos sexos,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,1.927
2,4,Ambos sexos,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,49.409
3,4,Ambos sexos,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,7.469
4,4,Ambos sexos,466 Bronquitis y bronquiolitis aguda,5.578
...,...,...,...,...
1711,52,Mujeres,Resto (460-478) Otras infecciones respiratoria...,133
1712,52,Mujeres,480-486 NeumonÃ­a,533
1713,52,Mujeres,487-488 Gripe,6
1714,52,Mujeres,"490-492,494,496 Enfermedad pulmonar obstructiv...",96
1715,52,Mujeres,493 Asma,67

In [249]:
data_2013.to_csv('Hospitalizaciones_2013.csv', index = False)

In [11]:
data_2014['Provincia, Comunidad y Ciudad autÃ³noma de residencia'] = data_2014['Provincia, Comunidad y Ciudad autÃ³noma de residencia'].str.lower().replace( {
    "araba/Ã¡lava": 1,
    "albacete": 2,
    "alicante/alacant": 3,
    "almerÃ­a": 4,
    "Ã¡vila": 5,
    "badajoz": 6,
    "balears, illes": 7,
    "barcelona": 8,
    "burgos": 9,
    "cÃ¡ceres": 10,
    "cÃ¡diz": 11,
    "castellÃ³n/castellÃ³": 12,
    "ciudad real": 13,
    "cÃ³rdoba": 14,
    "corunÌƒa, a": 15,
    "cuenca": 16,
    "girona": 17,
    "granada": 18,
    "guadalajara": 19,
    "gipuzkoa": 20,
    "huelva": 21,
    "huesca": 22,
    "jaÃ©n": 23,
    "leÃ³n": 24,
    "lleida": 25,
    "rioja, la": 26,
    "lugo": 27,
    "madrid, comunidad de": 28,
    "mÃ¡laga": 29,
    "murcia, regiÃ³n de": 30,
    "navarra, comunidad foral de": 31,
    "ourense": 32,
    "asturias, principado de": 33,
    "palencia": 34,
    "palmas, las": 35,
    "pontevedra": 36,
    "salamanca": 37,
    "santa cruz de tenerife": 38,
    "cantabria": 39,
    "segovia": 40,
    "sevilla": 41,
    "soria": 42,
    "tarragona": 43,
    "teruel": 44,
    "toledo": 45,
    "valencia/valÃ¨ncia": 46,
    "valladolid": 47,
    "bizkaia": 48,
    "zamora": 49,
    "zaragoza": 50,
    "ceuta": 51,
    "melilla": 52
}
                                                                                                                 )   
data_2014.head(50)

,"Provincia, Comunidad y Ciudad autÃ³noma de residencia",DiagnÃ³stico principal (CIE9MC),Sexo,Total
0,4,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Ambos sexos,4.532
1,4,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Hombres,3.806
2,4,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Mujeres,726
3,4,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Ambos sexos,2.087
4,4,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Hombres,972
5,4,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Mujeres,1.115
6,4,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Ambos sexos,49.306
7,4,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Hombres,28.690
8,4,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Mujeres,20.615
9,4,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Ambos sexos,8.614
10,4,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Hombres,3.995
11,4,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Mujeres,4.619
12,4,466 Bronquitis y bronquiolitis aguda,Ambos sexos,6.566
13,4,466 Bronquitis y bronquiolitis aguda,Hombres,2.752
14,4,466 Bronquitis y bronquiolitis aguda,Mujeres,3.814
15,4,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Ambos sexos,291
16,4,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Hombres,139
17,4,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Mujeres,152
18,4,Resto (460-478) Otras infecciones respiratoria...,Ambos sexos,1.756
19,4,Resto (460-478) Otras infecciones respiratoria...,Hombres,1.103
20,4,Resto (460-478) Otras infecciones respiratoria...,Mujeres,653
21,4,480-486 NeumonÃ­a,Ambos sexos,14.242
22,4,480-486 NeumonÃ­a,Hombres,8.526
23,4,480-486 NeumonÃ­a,Mujeres,5.716
24,4,487-488 Gripe,Ambos sexos,698
25,4,487-488 Gripe,Hombres,332
26,4,487-488 Gripe,Mujeres,366
27,4,"490-492,494,496 Enfermedad pulmonar obstructiv...",Ambos sexos,8.864
28,4,"490-492,494,496 Enfermedad pulmonar obstructiv...",Hombres,7.593
29,4,"490-492,494,496 Enfermedad pulmonar obstructiv...",Mujeres,1.271
30,4,493 Asma,Ambos sexos,1.777
31,4,493 Asma,Hombres,594
32,4,493 Asma,Mujeres,1.183
33,11,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Ambos sexos,7.575
34,11,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Hombres,6.227
35,11,"162 Neoplasia maligna de trÃ¡quea, bronquios y ...",Mujeres,1.348
36,11,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Ambos sexos,3.367
37,11,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Hombres,1.381
38,11,415-417 VII.5 ENFERMEDADES DE LA CIRCULACIÃ“N P...,Mujeres,1.986
39,11,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Ambos sexos,71.392
40,11,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Hombres,40.487
41,11,460-519 VIII ENFERMEDADES DEL APARATO RESPIRAT...,Mujeres,30.904
42,11,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Ambos sexos,11.464
43,11,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Hombres,6.141
44,11,460-478 VIII.1 INFECCIONES RESPIRATORIAS AGUDA...,Mujeres,5.323
45,11,466 Bronquitis y bronquiolitis aguda,Ambos sexos,6.767
46,11,466 Bronquitis y bronquiolitis aguda,Hombres,3.395
47,11,466 Bronquitis y bronquiolitis aguda,Mujeres,3.372
48,11,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Ambos sexos,622
49,11,474 Enfermedad crÃ³nica de amÃ­gdalas y adenoides,Hombres,312

In [5]:
data_2014.rename(
    columns = {'Provincia, Comunidad y Ciudad autÃ³noma de residencia': 'Provincia_ID'},
    inplace = True
)
data_2014.head(30)

NameError: name 'data_2014' is not defined

In [255]:
data_2014.to_csv('Hospitalizaciones_2014.csv', index = False)

In [39]:
data_2015['Provincia, Comunidad y Ciudad autÃ³noma de residencia'] = data_2015['Provincia, Comunidad y Ciudad autÃ³noma de residencia'].str.lower().replace( {
    "araba/Ã¡lava": 1,
    "albacete": 2,
    "alicante/alacant": 3,
    "almerÃ­a": 4,
    "Ã¡vila": 5,
    "badajoz": 6,
    "balears, illes": 7,
    "barcelona": 8,
    "burgos": 9,
    "cÃ¡ceres": 10,
    "cÃ¡diz": 11,
    "castellÃ³n/castellÃ³": 12,
    "ciudad real": 13,
    "cÃ³rdoba": 14,
    "corunÌƒa, a": 15,
    "cuenca": 16,
    "girona": 17,
    "granada": 18,
    "guadalajara": 19,
    "gipuzkoa": 20,
    "huelva": 21,
    "huesca": 22,
    "jaÃ©n": 23,
    "leÃ³n": 24,
    "lleida": 25,
    "rioja, la": 26,
    "lugo": 27,
    "madrid, comunidad de": 28,
    "mÃ¡laga": 29,
    "murcia, regiÃ³n de": 30,
    "navarra, comunidad foral de": 31,
    "ourense": 32,
    "asturias, principado de": 33,
    "palencia": 34,
    "palmas, las": 35,
    "pontevedra": 36,
    "salamanca": 37,
    "santa cruz de tenerife": 38,
    "cantabria": 39,
    "segovia": 40,
    "sevilla": 41,
    "soria": 42,
    "tarragona": 43,
    "teruel": 44,
    "toledo": 45,
    "valencia/valÃ¨ncia": 46,
    "valladolid": 47,
    "bizkaia": 48,
    "zamora": 49,
    "zaragoza": 50,
    "ceuta": 51,
    "melilla": 52
}
                                                                                                                 )   
data_2015.head(50)

,Sexo,DiagnÃ³stico principal (CIE9MC),"Provincia, Comunidad y Ciudad autÃ³noma de residencia",Total
0,Ambos sexos,TODAS LAS CAUSAS,total nacional,31.624.525
1,Ambos sexos,TODAS LAS CAUSAS,andalucÃ­a,4.275.428
2,Ambos sexos,TODAS LAS CAUSAS,4,355.472
3,Ambos sexos,TODAS LAS CAUSAS,11,683.033
4,Ambos sexos,TODAS LAS CAUSAS,14,394.417
5,Ambos sexos,TODAS LAS CAUSAS,18,467.567
6,Ambos sexos,TODAS LAS CAUSAS,21,301.598
7,Ambos sexos,TODAS LAS CAUSAS,23,341.533
8,Ambos sexos,TODAS LAS CAUSAS,29,807.255
9,Ambos sexos,TODAS LAS CAUSAS,41,924.553
10,Ambos sexos,TODAS LAS CAUSAS,aragÃ³n,1.083.703
11,Ambos sexos,TODAS LAS CAUSAS,22,180.647
12,Ambos sexos,TODAS LAS CAUSAS,44,108.149
13,Ambos sexos,TODAS LAS CAUSAS,50,794.906
14,Ambos sexos,TODAS LAS CAUSAS,33,873.578
15,Ambos sexos,TODAS LAS CAUSAS,7,727.687
16,Ambos sexos,TODAS LAS CAUSAS,canarias,1.258.042
17,Ambos sexos,TODAS LAS CAUSAS,35,604.187
18,Ambos sexos,TODAS LAS CAUSAS,38,653.855
19,Ambos sexos,TODAS LAS CAUSAS,39,461.441
20,Ambos sexos,TODAS LAS CAUSAS,castilla y leÃ³n,1.979.898
21,Ambos sexos,TODAS LAS CAUSAS,5,133.532
22,Ambos sexos,TODAS LAS CAUSAS,9,284.852
23,Ambos sexos,TODAS LAS CAUSAS,24,488.645
24,Ambos sexos,TODAS LAS CAUSAS,34,163.479
25,Ambos sexos,TODAS LAS CAUSAS,37,209.957
26,Ambos sexos,TODAS LAS CAUSAS,40,99.599
27,Ambos sexos,TODAS LAS CAUSAS,42,77.549
28,Ambos sexos,TODAS LAS CAUSAS,47,375.758
29,Ambos sexos,TODAS LAS CAUSAS,49,146.526
30,Ambos sexos,TODAS LAS CAUSAS,castilla - la mancha,1.234.710
31,Ambos sexos,TODAS LAS CAUSAS,2,226.317
32,Ambos sexos,TODAS LAS CAUSAS,13,326.407
33,Ambos sexos,TODAS LAS CAUSAS,16,144.167
34,Ambos sexos,TODAS LAS CAUSAS,19,137.525
35,Ambos sexos,TODAS LAS CAUSAS,45,400.293
36,Ambos sexos,TODAS LAS CAUSAS,cataluÃ±a,6.094.113
37,Ambos sexos,TODAS LAS CAUSAS,8,4.606.772
38,Ambos sexos,TODAS LAS CAUSAS,17,491.545
39,Ambos sexos,TODAS LAS CAUSAS,25,333.182
40,Ambos sexos,TODAS LAS CAUSAS,43,662.614
41,Ambos sexos,TODAS LAS CAUSAS,comunitat valenciana,2.711.008
42,Ambos sexos,TODAS LAS CAUSAS,3,1.044.560
43,Ambos sexos,TODAS LAS CAUSAS,12,330.074
44,Ambos sexos,TODAS LAS CAUSAS,46,1.336.373
45,Ambos sexos,TODAS LAS CAUSAS,extremadura,787.514
46,Ambos sexos,TODAS LAS CAUSAS,6,465.585
47,Ambos sexos,TODAS LAS CAUSAS,10,321.929
48,Ambos sexos,TODAS LAS CAUSAS,galicia,2.100.915
49,Ambos sexos,TODAS LAS CAUSAS,"coruÃ±a, a",806.427

In [41]:
data_2015.rename(
    columns = {'Provincia, Comunidad y Ciudad autÃ³noma de residencia': 'Provincia_ID'},
    inplace = True
)
data_2015

              Sexo DiagnÃ³stico principal (CIE9MC)    Provincia_ID       Total
0      Ambos sexos               TODAS LAS CAUSAS  total nacional  31.624.525
1      Ambos sexos               TODAS LAS CAUSAS       andalucÃ­a   4.275.428
2      Ambos sexos               TODAS LAS CAUSAS               4     355.472
3      Ambos sexos               TODAS LAS CAUSAS              11     683.033
4      Ambos sexos               TODAS LAS CAUSAS              14     394.417
...            ...                            ...             ...         ...
38203      Mujeres          ALTAS SIN DIAGNÃ“STICO              20       3.866
38204      Mujeres          ALTAS SIN DIAGNÃ“STICO              26         207
38205      Mujeres          ALTAS SIN DIAGNÃ“STICO              51           2
38206      Mujeres          ALTAS SIN DIAGNÃ“STICO              52          44
38207      Mujeres          ALTAS SIN DIAGNÃ“STICO      extranjero         327

[38208 rows x 4 columns]

In [43]:
data_2015.to_csv('Hospitalizaciones_2015.csv', index = False)