# Limpieza de datos de hospitalizaciones 2019

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df19 = pd.read_csv("1-2019.csv", delimiter= ";", encoding = "latin1")

df19.columns = df19.columns.str.strip()

In [3]:
# Mostrar los nombres de columnas para verificar
print("Columnas de df19:", df19.columns)

Columnas de df19: Index(['Diagnóstico principal (CIE10MC)', 'Total Nacional',
       'Comunidades y Ciudades Autónomas', 'Provincias', 'Sexo', 'Total'],
      dtype='object')

In [4]:
df19.head(10)

,Diagnóstico principal (CIE10MC),Total Nacional,Comunidades y Ciudades Autónomas,Provincias,Sexo,Total
0,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,04 Almería,Ambos sexos,4.485
1,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,04 Almería,Hombres,3.614
2,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,04 Almería,Mujeres,872.000
3,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,11 Cádiz,Ambos sexos,8.142
4,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,11 Cádiz,Hombres,6.472
5,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,11 Cádiz,Mujeres,1.670
6,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,14 Córdoba,Ambos sexos,3.303
7,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,14 Córdoba,Hombres,2.617
8,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,14 Córdoba,Mujeres,686.000
9,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,18 Granada,Ambos sexos,5.372

In [5]:
df19.dtypes

Diagnóstico principal (CIE10MC)      object
Total Nacional                       object
Comunidades y Ciudades Autónomas     object
Provincias                           object
Sexo                                 object
Total                               float64
dtype: object

In [6]:
# LIMPIEZA COLUMNA TOTAL
df19['Total'] = df19['Total'].astype(str).str.replace('.', '', regex=False).astype(int)

In [7]:
df19.dtypes

Diagnóstico principal (CIE10MC)     object
Total Nacional                      object
Comunidades y Ciudades Autónomas    object
Provincias                          object
Sexo                                object
Total                                int64
dtype: object

In [8]:
df19['Total'].isnull().sum()

0

In [9]:
# CREACIÓN DE COLUMNA PROVINCIAS
df19['Comunidades y Ciudades Autónomas'] = df19['Comunidades y Ciudades Autónomas'].fillna('')
df19['Provincias'] = df19['Provincias'].fillna('')

In [10]:
df19['Combinada'] = df19['Comunidades y Ciudades Autónomas'].str.cat(df19['Provincias'], sep=' ')

In [11]:
df19.head(1)

,Diagnóstico principal (CIE10MC),Total Nacional,Comunidades y Ciudades Autónomas,Provincias,Sexo,Total,Combinada
0,"0202 Neoplasias malignas de tráquea, bronquios...",Total Nacional,01 Andalucía,04 Almería,Ambos sexos,4485,01 Andalucía 04 Almería

In [12]:
df19 = df19[df19.columns[[0,4,5,6]]]

In [13]:
df19

,Diagnóstico principal (CIE10MC),Sexo,Total,Combinada
0,"0202 Neoplasias malignas de tráquea, bronquios...",Ambos sexos,4485,01 Andalucía 04 Almería
1,"0202 Neoplasias malignas de tráquea, bronquios...",Hombres,3614,01 Andalucía 04 Almería
2,"0202 Neoplasias malignas de tráquea, bronquios...",Mujeres,8720,01 Andalucía 04 Almería
3,"0202 Neoplasias malignas de tráquea, bronquios...",Ambos sexos,8142,01 Andalucía 11 Cádiz
4,"0202 Neoplasias malignas de tráquea, bronquios...",Hombres,6472,01 Andalucía 11 Cádiz
...,...,...,...,...
1555,1008 Otras enfermedades del aparato respirator...,Hombres,9410,18 Ceuta
1556,1008 Otras enfermedades del aparato respirator...,Mujeres,6520,18 Ceuta
1557,1008 Otras enfermedades del aparato respirator...,Ambos sexos,3024,19 Melilla
1558,1008 Otras enfermedades del aparato respirator...,Hombres,151,19 Melilla
1559,1008 Otras enfermedades del aparato respirator...,Mujeres,1514,19 Melilla

In [14]:
df19['Combinada'].unique()

array(['01 Andalucía 04 Almería', '01 Andalucía 11 Cádiz',
       '01 Andalucía 14 Córdoba', '01 Andalucía 18 Granada',
       '01 Andalucía 21 Huelva', '01 Andalucía 23 Jaén',
       '01 Andalucía 29 Málaga', '01 Andalucía 41 Sevilla',
       '02 Aragón 22 Huesca', '02 Aragón 44 Teruel',
       '02 Aragón 50 Zaragoza', '03 Asturias, Principado de ',
       '04 Balears, Illes ', '05 Canarias 35 Palmas, Las',
       '05 Canarias 38 Santa Cruz de Tenerife', '06 Cantabria ',
       '07 Castilla y León 05 Ávila', '07 Castilla y León 09 Burgos',
       '07 Castilla y León 24 León', '07 Castilla y León 34 Palencia',
       '07 Castilla y León 37 Salamanca', '07 Castilla y León 40 Segovia',
       '07 Castilla y León 42 Soria', '07 Castilla y León 47 Valladolid',
       '07 Castilla y León 49 Zamora',
       '08 Castilla - La Mancha 02 Albacete',
       '08 Castilla - La Mancha 13 Ciudad Real',
       '08 Castilla - La Mancha 16 Cuenca',
       '08 Castilla - La Mancha 19 Guadalajara',
       '08 Castilla - La Mancha 45 Toledo', '09 Cataluña 08 Barcelona',
       '09 Cataluña 17 Girona', '09 Cataluña 25 Lleida',
       '09 Cataluña 43 Tarragona',
       '10 Comunitat Valenciana 03 Alicante/Alacant',
       '10 Comunitat Valenciana 12 Castellón/Castelló',
       '10 Comunitat Valenciana 46 Valencia/València',
       '11 Extremadura 06 Badajoz', '11 Extremadura 10 Cáceres',
       '12 Galicia 15 Coruña, A', '12 Galicia 27 Lugo',
       '12 Galicia 32 Ourense', '12 Galicia 36 Pontevedra',
       '13 Madrid, Comunidad de ', '14 Murcia, Región de ',
       '15 Navarra, Comunidad Foral de ', '16 País Vasco 01 Araba/Álava',
       '16 País Vasco 48 Bizkaia', '16 País Vasco 20 Gipuzkoa',
       '17 Rioja, La ', '18 Ceuta ', '19 Melilla '], dtype=object)

In [15]:
# RENOMBRADO DE COLUMNAS
df19.rename(
    columns = {'Combinada': 'Provincia',
              'Diagnóstico principal (CIE10MC)': 'Diagnóstico',
              'Total': 'Hospitalizaciones'},
    inplace = True
)

In [16]:
df19 = df19[['Diagnóstico', 'Provincia', 'Sexo', 'Hospitalizaciones']]

In [17]:
mapeo_combinada = {
    '01 Andalucía 04 Almería': 'Almería',
    '01 Andalucía 11 Cádiz': 'Cádiz',
    '01 Andalucía 14 Córdoba': 'Córdoba',
    '01 Andalucía 18 Granada': "Granada",
    '01 Andalucía 21 Huelva': 'Huelva',
    '01 Andalucía 23 Jaén': 'Jaén',
    '01 Andalucía 29 Málaga': 'Málaga',
    '01 Andalucía 41 Sevilla': 'Sevilla',
    '02 Aragón 22 Huesca': 'Huesca',
    '02 Aragón 44 Teruel': 'Teruel',
    '02 Aragón 50 Zaragoza': 'Zaragoza',
    '03 Asturias, Principado de ': 'Asturias',
    '04 Balears, Illes ': 'Islas Baleares',
    '05 Canarias 35 Las Palmas': 'Las Palmas',
    '05 Canarias 38 Santa Cruz de Tenerife': 'Santa Cruz de Tenerife',
    '06 Cantabria ': 'Cantabria',
    '07 Castilla y León 05 Ávila': 'Ávila',
    '07 Castilla y León 09 Burgos': 'Burgos',
    '07 Castilla y León 24 León': 'León',
    '07 Castilla y León 34 Palencia': 'Palencia',
    '07 Castilla y León 37 Salamanca': 'Salamanca',
    '07 Castilla y León 40 Segovia': 'Segovia',
    '07 Castilla y León 42 Soria': 'Soria',
    '07 Castilla y León 47 Valladolid': 'Valladolid',
    '07 Castilla y León 49 Zamora': 'Zamora',
    '08 Castilla - La Mancha 02 Albacete': 'Albacete',
    '08 Castilla - La Mancha 13 Ciudad Real': 'Ciudad Real',
    '08 Castilla - La Mancha 16 Cuenca': 'Cuenca',
    '08 Castilla - La Mancha 19 Guadalajara': 'Guadalajara',
    '08 Castilla - La Mancha 45 Toledo': 'Toledo',
    '09 Cataluña 08 Barcelona': 'Barcelona',
    '09 Cataluña 17 Girona': 'Girona',
    '09 Cataluña 25 Lleida': 'Lleida',
    '09 Cataluña 43 Tarragona': 'Tarragona',
    '10 Comunitat Valenciana 03 Alicante/Alacant': 'Alicante',
    '10 Comunitat Valenciana 12 Castellón/Castelló': 'Castellón',
    '10 Comunitat Valenciana 46 Valencia/València': 'Valencia',
    '11 Extremadura 06 Badajoz': 'Badajoz',
    '11 Extremadura 10 Cáceres': 'Cáceres',
    '12 Galicia 15 Coruña, A': 'A Coruña',
    '12 Galicia 27 Lugo': 'Lugo',
    '12 Galicia 32 Ourense': 'Ourense',
    '12 Galicia 36 Pontevedra': 'Pontevedra',
    '13 Madrid, Comunidad de ': 'Madrid',
    '14 Murcia, Región de ': 'Murcia',
    '15 Navarra, Comunidad Foral de ': 'Navarra',
    '16 País Vasco 01 Araba/Álava': 'Álava',
    '16 País Vasco 48 Bizkaia': 'Bizkaia',
    '16 País Vasco 20 Gipuzkoa': 'Gipuzkoa',
    '17 Rioja, La ': 'La Rioja',
    '18 Ceuta ': 'Ceuta',
    '19 Melilla ': 'Melilla'
}

df19['Provincia'] = df19['Provincia'].map(mapeo_combinada)

In [18]:
# Crear un filtro para seleccionar filas donde "Provincia" es NaN
filtro = df19['Provincia'].isna()

# Aplicar el filtro para obtener solo las filas donde "Provincia" es NaN
df19_nan_provincia = df19.loc[filtro]

# Mostrar el resultado
df19_nan_provincia

,Diagnóstico,Provincia,Sexo,Hospitalizaciones
39,"0202 Neoplasias malignas de tráquea, bronquios...",NaN,Ambos sexos,8683
40,"0202 Neoplasias malignas de tráquea, bronquios...",NaN,Hombres,6501
41,"0202 Neoplasias malignas de tráquea, bronquios...",NaN,Mujeres,2182
195,0905 Enfermedad pulmonar cardíaca y enfermedad...,NaN,Ambos sexos,439
196,0905 Enfermedad pulmonar cardíaca y enfermedad...,NaN,Hombres,1651
197,0905 Enfermedad pulmonar cardíaca y enfermedad...,NaN,Mujeres,2739
351,1001 Infecciones agudas de las vías respirator...,NaN,Ambos sexos,6597
352,1001 Infecciones agudas de las vías respirator...,NaN,Hombres,283
353,1001 Infecciones agudas de las vías respirator...,NaN,Mujeres,3767
507,1002 Neumonía J12-J18,NaN,Ambos sexos,2613
508,1002 Neumonía J12-J18,NaN,Hombres,14029
509,1002 Neumonía J12-J18,NaN,Mujeres,121
663,1003 Otras infecciones agudas de las vias resp...,NaN,Ambos sexos,10677
664,1003 Otras infecciones agudas de las vias resp...,NaN,Hombres,4132
665,1003 Otras infecciones agudas de las vias resp...,NaN,Mujeres,6545
819,1004 Enfermedad crónica de amígdalas y adenoid...,NaN,Ambos sexos,6030
820,1004 Enfermedad crónica de amígdalas y adenoid...,NaN,Hombres,3380
821,1004 Enfermedad crónica de amígdalas y adenoid...,NaN,Mujeres,2640
975,1005 Otras enfermedades del tracto respiratori...,NaN,Ambos sexos,2303
976,1005 Otras enfermedades del tracto respiratori...,NaN,Hombres,1105
977,1005 Otras enfermedades del tracto respiratori...,NaN,Mujeres,1198
1131,1006 Enfermedad pulmonar obstructiva crónica y...,NaN,Ambos sexos,15893
1132,1006 Enfermedad pulmonar obstructiva crónica y...,NaN,Hombres,9946
1133,1006 Enfermedad pulmonar obstructiva crónica y...,NaN,Mujeres,5947
1287,1007 Asma J45,NaN,Ambos sexos,213
1288,1007 Asma J45,NaN,Hombres,5800
1289,1007 Asma J45,NaN,Mujeres,155
1443,1008 Otras enfermedades del aparato respirator...,NaN,Ambos sexos,44504
1444,1008 Otras enfermedades del aparato respirator...,NaN,Hombres,19565
1445,1008 Otras enfermedades del aparato respirator...,NaN,Mujeres,24939

In [19]:
df19 = df19.dropna()

In [20]:
df19.head(3)

,Diagnóstico,Provincia,Sexo,Hospitalizaciones
0,"0202 Neoplasias malignas de tráquea, bronquios...",Almería,Ambos sexos,4485
1,"0202 Neoplasias malignas de tráquea, bronquios...",Almería,Hombres,3614
2,"0202 Neoplasias malignas de tráquea, bronquios...",Almería,Mujeres,8720

In [21]:
# CREACIÓN DE OTRA COLUMNA PROVINCIA ID
columna_duplicada = df19['Provincia']
if 'ColumnaDuplicada' in df19.columns:
    df19.drop(columns=['ColumnaDuplicada'], inplace=True)
df19.insert(2, 'ColumnaDuplicada', columna_duplicada)

In [22]:
df19.rename(
    columns = {'ColumnaDuplicada': 'Provincia_ID'},
    inplace = True
)

In [23]:
mapeo_provincias = {
    "Álava": 1,
    "Albacete": 2,
    "Alicante": 3,
    "Almería": 4,
    "Ávila": 5,
    "Badajoz": 6,
    "Islas Baleares": 7,
    "Barcelona": 8,
    "Burgos": 9,
    "Cáceres": 10,
    "Cádiz": 11,
    "Castellón": 12,
    "Ciudad Real": 13,
    "Córdoba": 14,
    "A Coruña": 15,
    "Cuenca": 16,
    "Girona": 17,
    "Granada": 18,
    "Guadalajara": 19,
    "Gipuzkoa": 20,
    "Huelva": 21,
    "Huesca": 22,
    "Jaén": 23,
    "León": 24,
    "Lleida": 25,
    "La Rioja": 26,
    "Lugo": 27,
    "Madrid": 28,
    "Málaga": 29,
    "Murcia": 30,
    "Navarra": 31,
    "Ourense": 32,
    "Asturias": 33,
    "Palencia": 34,
    "Las Palmas": 35,
    "Pontevedra": 36,
    "Salamanca": 37,
    "Santa Cruz de Tenerife": 38,
    "Cantabria": 39,
    "Segovia": 40,
    "Sevilla": 41,
    "Soria": 42,
    "Tarragona": 43,
    "Teruel": 44,
    "Toledo": 45,
    "Valencia": 46,
    "Valladolid": 47,
    "Bizkaia": 48,
    "Zamora": 49,
    "Zaragoza": 50,
    "Ceuta": 51,
    "Melilla": 52
}

df19['Provincia_ID'] = df19['Provincia_ID'].map(mapeo_provincias)

In [24]:
df19.head()

,Diagnóstico,Provincia,Provincia_ID,Sexo,Hospitalizaciones
0,"0202 Neoplasias malignas de tráquea, bronquios...",Almería,4,Ambos sexos,4485
1,"0202 Neoplasias malignas de tráquea, bronquios...",Almería,4,Hombres,3614
2,"0202 Neoplasias malignas de tráquea, bronquios...",Almería,4,Mujeres,8720
3,"0202 Neoplasias malignas de tráquea, bronquios...",Cádiz,11,Ambos sexos,8142
4,"0202 Neoplasias malignas de tráquea, bronquios...",Cádiz,11,Hombres,6472

In [25]:
df19['Provincia_ID'].isna().sum()

0

In [26]:
df19['Diagnóstico'].unique()

array(['0202 Neoplasias malignas de tráquea, bronquios y pulmón C33-C34',
       '0905 Enfermedad pulmonar cardíaca y enfermedades de la circulación pulmonar I26-I28',
       '1001 Infecciones agudas de las vías respiratorias superiores y gripe J00-J11',
       '1002 Neumonía J12-J18',
       '1003 Otras infecciones agudas de las vias respiratorias inferiores J20-J22',
       '1004 Enfermedad crónica de amígdalas y adenoides J35',
       '1005 Otras enfermedades del tracto respiratorio superior J30-J34, J36-J39',
       '1006 Enfermedad pulmonar obstructiva crónica y bronquiectasias J40-J44, J47',
       '1007 Asma J45',
       '1008 Otras enfermedades del aparato respiratorio J60-J99'],
      dtype=object)

In [27]:
# SIMPLIFICACIÓN DE NOMBRES EN COLUMNA DIAGNÓSTICO
mapeo_diagnostico = {
    '0202 Neoplasias malignas de tráquea, bronquios y pulmón C33-C34': "Neoplasia maligna de tráquea, bronquios y pulmón",
    '0905 Enfermedad pulmonar cardíaca y enfermedades de la circulación pulmonar I26-I28': "Enfermedades de la circulación pulmonar",
    '1001 Infecciones agudas de las vías respiratorias superiores y gripe J00-J11': 'Infecciones/enfermedades de las vías respiratorias superiores y gripe',
    '1002 Neumonía J12-J18': 'Neumonía',
    '1003 Otras infecciones agudas de las vias respiratorias inferiores J20-J22':'Otras infecciones de las vías respiratorias inferiores',
    '1004 Enfermedad crónica de amígdalas y adenoides J35': 'Enfermedad crónica de amígdalas',
    '1005 Otras enfermedades del tracto respiratorio superior J30-J34, J36-J39': 'Infecciones/enfermedades de las vías respiratorias superiores y gripe',
    '1006 Enfermedad pulmonar obstructiva crónica y bronquiectasias J40-J44, J47': 'EPOC y bronquitis',
    '1007 Asma J45': 'Asma',
    '1008 Otras enfermedades del aparato respiratorio J60-J99': 'Neumoconiosis, enfermedades pulmonares por agentes externos y otras'
}

df19['Diagnóstico'] = df19['Diagnóstico'].map(mapeo_diagnostico)

In [28]:
df19.insert(0, 'Año', 2019)

In [29]:
df19 = df19[df19['Sexo'] != 'Ambos sexos']

In [30]:
df19

,Año,Diagnóstico,Provincia,Provincia_ID,Sexo,Hospitalizaciones
1,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Almería,4,Hombres,3614
2,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Almería,4,Mujeres,8720
4,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Cádiz,11,Hombres,6472
5,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Cádiz,11,Mujeres,167
7,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Córdoba,14,Hombres,2617
...,...,...,...,...,...,...
1553,2019,"Neumoconiosis, enfermedades pulmonares por age...",La Rioja,26,Mujeres,4478
1555,2019,"Neumoconiosis, enfermedades pulmonares por age...",Ceuta,51,Hombres,9410
1556,2019,"Neumoconiosis, enfermedades pulmonares por age...",Ceuta,51,Mujeres,6520
1558,2019,"Neumoconiosis, enfermedades pulmonares por age...",Melilla,52,Hombres,151
1559,2019,"Neumoconiosis, enfermedades pulmonares por age...",Melilla,52,Mujeres,1514

In [31]:
df19 = df19.reset_index()

In [32]:
df19.drop('index', axis=1, inplace=True)

In [33]:
df19

,Año,Diagnóstico,Provincia,Provincia_ID,Sexo,Hospitalizaciones
0,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Almería,4,Hombres,3614
1,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Almería,4,Mujeres,8720
2,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Cádiz,11,Hombres,6472
3,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Cádiz,11,Mujeres,167
4,2019,"Neoplasia maligna de tráquea, bronquios y pulmón",Córdoba,14,Hombres,2617
...,...,...,...,...,...,...
1015,2019,"Neumoconiosis, enfermedades pulmonares por age...",La Rioja,26,Mujeres,4478
1016,2019,"Neumoconiosis, enfermedades pulmonares por age...",Ceuta,51,Hombres,9410
1017,2019,"Neumoconiosis, enfermedades pulmonares por age...",Ceuta,51,Mujeres,6520
1018,2019,"Neumoconiosis, enfermedades pulmonares por age...",Melilla,52,Hombres,151
1019,2019,"Neumoconiosis, enfermedades pulmonares por age...",Melilla,52,Mujeres,1514

In [34]:
df19["Diagnóstico"].unique()

array(['Neoplasia maligna de tráquea, bronquios y pulmón',
       'Enfermedades de la circulación pulmonar',
       'Infecciones/enfermedades de las vías respiratorias superiores y gripe',
       'Neumonía',
       'Otras infecciones de las vías respiratorias inferiores',
       'Enfermedad crónica de amígdalas', 'EPOC y bronquitis', 'Asma',
       'Neumoconiosis, enfermedades pulmonares por agentes externos y otras'],
      dtype=object)

In [35]:
# CREACIÓN COLUMNA DIAGNÓSTICO ID
columna_duplicada = df19['Diagnóstico']
if 'ColumnaDuplicada' in df19.columns:
    df19.drop(columns=['ColumnaDuplicada'], inplace=True)
df19.insert(2, 'ColumnaDuplicada', columna_duplicada)

In [36]:
df19.rename(
    columns = {'ColumnaDuplicada': 'Diagnóstico_ID'},
    inplace = True
)

In [37]:
mapeo_diagnostico = {
    'Neoplasia maligna de tráquea, bronquios y pulmón': 1,
    'Enfermedades de la circulación pulmonar':2,
    'Enfermedad crónica de amígdalas': 3,
    'Neumonía': 4,
    'Asma': 5,
    'EPOC y bronquitis': 6,
    'Infecciones/enfermedades de las vías respiratorias superiores y gripe': 7,
    'Otras infecciones de las vías respiratorias inferiores': 8,
    'Neumoconiosis, enfermedades pulmonares por agentes externos y otras': 9
}

df19['Diagnóstico_ID'] = df19['Diagnóstico_ID'].map(mapeo_diagnostico)

In [38]:
df19['Diagnóstico_ID'].unique()

array([1, 2, 7, 4, 8, 3, 6, 5, 9])

In [39]:
df19 = df19.groupby(['Diagnóstico_ID','Año','Diagnóstico','Sexo','Provincia','Provincia_ID'])['Hospitalizaciones'].sum().reset_index()

In [42]:
df19.to_csv("df19.csv", index=False, encoding="iso-8859-1")